# -*- mode: ruby -*-
# vi: set ft=ruby :

MACHINE_NAME="modern-historian"
ANSIBLE_PLAYBOOK="../../../ansible/playbook.yml"
DEBUG = false; # true to see stdout

=begin
OPCUA Server port: 4334
InfluxDB2 port: 8086
Traefik ports: 8081, 6443
=end
FORWARDED_PORTS=[4334, 6443, 8081, 8086]

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/focal64"
  config.vm.hostname = "#{MACHINE_NAME}"
  config.vm.define "#{MACHINE_NAME}"
  config.ssh.insert_key = false

  FORWARDED_PORTS.each do |port|
    config.vm.network "forwarded_port", guest: port, host: port
  end

  config.vm.provider "virtualbox" do |vb|
    vb.name = "#{MACHINE_NAME}"
  end

  config.vm.provision "ansible" do |ansible|
    ansible.verbose = DEBUG # true to see stdout
    ansible.compatibility_mode = "2.0"
    ansible.playbook = "#{ANSIBLE_PLAYBOOK}"
  end
end
