---
# tasks file for indaco.influxdb2

- name: Create 'influxdb2/data' folder if not exists
  ansible.builtin.file:
    path: '{{ influxdb2_data_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'influxdb2/config' folder if not exists
  ansible.builtin.file:
    path: '{{ influxdb2_config_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Create 'influxdb2/tasks' folder if not exists
  ansible.builtin.file:
    path: '{{ influxdb2_tasks_path }}'
    state: directory
    owner: '{{ ansible_user }}'
    group: '{{ ansible_user }}'
    mode: '0755'

- name: Pull the Influxdb2 alpine docker image
  community.docker.docker_image:
    name: influxdb:alpine
    source: pull
  register: pullInfluxDB2
  until: pullInfluxDB2 is succeeded
  retries: 5
  delay: 4
